project:
  type: website
  output-dir: "."

website:
  title: "Abby Hofschneider"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© Abby Hofschneider, 2023"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: mybgcolor {background-color:#92bdd9; }, .myforecolor {color:#7d7eec; }
    toc: false
    include-after-body: target_blank.html
    
